### ISSUE TITLE
多余mod

### ISSUE THREAD

**Issue by zhangyina1** [meishiffx/CreativeDrawersProducerServer#1]
toomanyglyphs-1.18.1-2.0.7.15321.jar
ars_creo-1.18.2-2.1.4.jar
ars_elemental-1.18.2-0.4.9.9.jar
ars_instrumentum-1.18.2-2.5.0.jar
ars_nouveau-1.18.2-2.8.0.jar

这几个是多余的。。作者自己玩的时候添加的吧。。我下载了1.0.2和1.0.5都没有这几个mod

虽然能开服的应该都能解决，但是说不定有小白呢

**Comment by meishiffx** [comment]
我的问题，本地删除了没上传，已经删了
